# Consult https://github.com/codecov/support/wiki/Codecov-Yaml for docs.
codecov:
  notify:
    require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "80...100"  # Make 80% be angry red and 100% be happy green.

  status:
    project:
      default:
        enabled: yes
        target: auto  # Coverage must increase or remain constant
    patch:
      default:
        enabled: yes
        target: 100%  # Require 100% coverage on all PRs

  ignore:
    - "fedmsg/tests/*"

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
